sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
language: java
jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
install: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c17461eb5b3d00b3656d
    on_success: change
    on_failure: always
    on_start: never
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: Su/XAUnT2oKgzHdty6vkZeCsnE4Lx4aYRizUkWhHRquYKAzfT0lQDNpUFCKshKLW2P43/hIi92xlCDnd22YGf51RXIR4azJTs9/9TB4O5QMBuW/adhd4Pw50J4+FzXpKcEmn0XYCwvDsT65CQe/l2DBHQh7UeJamgjTYL4o25lLM5665qzZRPD/SkvSkKniK/qJZeyOyIH0jGsIxN7KnolxQ+/k7GvgPrbPoFlbzIVDrTBzJXBQ3B+TkA+ruxpj1yCnYpEs7IKJGVFelIig+TNWcJ2gSKA3G2hHQ7Kk9p/Ea8G5NCtVrUgGR+F5rEJtE8Uog+aCCvzu63dujBZlkzqfSlqEClzJ+G3eHnY4KFOC1h3YORFFjrud6oRtfQOlV+tiatgAmFNaNg5oQkEOUQnKHrPNRh+xGx9PPLvrRXtE7i47TWz+XRfzin7NyHp1orop6noRqg6PNuRwQDMS+dAWGP7CZ4iwBlkD1yDJr0jFWiDWITMLgcI7+UwiIlYVG/xCYRo/og+tcjx5bg+wPhLlbQ1c9ceMmwByHBuH0+rqoBXiWUOqivXtw7QbIwR7LkxJhAGFxonHZvxAxNgRiUo44/jskHnlFS59F3CVfVvYXyt4Y1WbppUdwi9ZoAJ3kP34vik/TLbhW7u/JshIMeUBUVs38oaN3ETkLig+lK3g=
  - secure: mYZN++dxSxj2jp1/PI7Lf81im3hXOTv56l3qzbCklQAmckYQWaSvzE8ULzK112dJicVOkCV0lOl1BECeY8RWi6kZEv4PqntNI8SpQ4A+GeRVJ2uT36hofx3NWtnA41NGUUuGTbjTWFKq1SjnjmIzH4gDAvtkSS7ul4ewLnsrPemKGUbm4DkXlPYDfauTk+5iXeHYgA2vdnepaLSBFiN6IKNjp5nZ1/XIBAp/TRNey6uWinJLE93wr09q5Bs+HCuyFXo1SsisEdG5gfH2jAmNL6puUFF6/z0v0LOJt1C0el4X+YAY2gDaOhU2hvqGdMyAloGJa5S/kFTbN3X0IpbCQgrzFxKNlrxyqU1HOg194b9NN43JqDT+uK9Y1z72mNo6Tlwygs8ELXvzih8sHnD+LNSTCMEU/7lPTsiujfWdGT8XPOuF1kNJKx9/yizeglvbA/5DthFIAjjfwpIkrNWEOuxDdfaS6gZN4gnQYObY+uxxBCMND643P+x5pd/7e0lR5ti7g/wTTGfFZ9Ki5UEWm9S75d0njW9sdWsqxrzIGkPtSVdZOrEFfTzcTVUBHEFfwyJ7ANDlkFdenFe0NGz1aXVGBdM+eGx3uOuMi7HtczOE+BtQW5V+oX4gU0J43rDIYYbhIMhi0b1bjaLumX1tlmW0W+HI87DON8I1izaMEME=
  - secure: KSqI8ST13Yr3IzCcGbLUiQbIw0cDkKTpkxhrMGGeK5WpdtYUkp8ol6j/ohLEZN3gC5h33UoAExnKR6j2SCnZV0Lw58v2HuTLlafPhGu4NrAqtgqdHBARFM+pbBja1A0Wy/EkriVXuo/8S2dEee8wz8xt8noUxW+Mw2De7uWDd9WMVH3Bil9TrgImtHJDUiWLyAECD/54an8P3Pi5+wR8BdyoNr+KI8SKE6cXISnn/btMh0KXS0ui0N5bXYiKRqaKbLjqm4yjJnsVZdm5a7i5AAbeKKEyxxWpkJQ520ZO1i5qe4+7bp6p842Dls7mJEzU4VJiuJ/q5Cruy64xwr0T5AGonm5GLFb/FY+MwdVkmz2mq/a1mThdojFNMRSJXlW7redzVCJys21wnVdUxPWXyw+U3SbMyg1GFWjuunXkQZ2h5+IEE62iSVmZyS4wFHiwwRB8lzqMPny2pXG+cpKvvWbWL46qN+bBIPK/Wb10eFvtB06axxM5u/drEXX+8wLHSTNN4Y7BxwQQVgeDuTu5j832YMTgjMbSgrF05oelQnkHujxNoorGYI1ITbtAjxZ0cjQVJ+jVzHeju9f8Z8H0s+QiHSDzJhGjyITQF65T1VHyJnqs8gJBxm8OAGGnDjCwDg6WNOek6StqE7T+9NJ67x25LZkXmbpAaFhUGxn4pY4=
  - secure: cbScxpz4vZte+FRWTwhgfy3VSD8HDJf06vhOkOHYMElaZyhwpB4EA+WBNrU7LNt7Fktl15L73SCbQ4U9pzJYM3Hi/M/tTLB1TKHeewPB+tcGintD6YjswWE91dJeci4GNN6Jq4KWTp/BrnJKAk0a7mIOzPVLJAuLfkl3pp3rxZwrjH7PMT884I6N2ViILQibu7ynkBn79QznA2YDtCw++GatlgJXgVswqixTx3kMj35Su3tyiYJFqICWXcwBQG3IzWV+eR1/msS0twSSx4K5z32lC5ajmi8gV+9zoeCqr8KcpOuXs0SHLERAFi3ig0R30EU5xEKESIkhU9YDjJmVKvz06MsijmK7pW0tRIVGDscF4dTNEZ7Pl06SNXGU/NNJQJd4ABWgZMVCokmB4HZ3iO9SEJQH9tho+x6IJ86xbmC0XKl7zWBeyROYCsgSlbiBXPOi+KTrGIR5HSw4+GIy/C906o7+u+RRKh6s63jE706L6dNp7YMlEDcj4k2NjtugEnzYrzqNTzOqR05VAHP7FNKWGYGACfrwbBAfgrzBdLDmY58L5l5EQBICwJ36Ligl5MDhP+OcAKn0l/o+6WNNBQyQeRTLli/uDuchCSIztVDS8w7SbKNzwV4vdpfs6c3qfIoCbS1CsbfR0HsQyNAfP3yxdA+ZwAPNsyZdicuJDrQ=
  - secure: C5IA0Yhn49kXFzgWpxc5YOx/J/e+AbJD9NVk410X4oYCXq6lMIapQV1nVtpL/rrArxeDjRlo2A8CU6jQXsHSziXCI6WLj5BWLvGzD6ld8yMu8GjQs8/uMBZUDHIUK0HF4G48f7hZ05+exBHT37VHt6NwFc8U9vdjpY6FxpqLZInoCJWK862lRMVztxXql3RDG1goebBJsq3eUAoiuGedKpay7kXBYKj8DbJAgPNwigWdV2WIgdyF6Hia89fLiqjKjPIUsGjll/34P0HFaInxycTWnNzMdu5KyGvod035N4xHzxf5LvUj+Alio2Az7tdQlbvnO8p8pcuMUK7sCcBqpcoeoDTR4FNaysj4DMTgkHGiHa3UuQQf5j6xnsRbkUkME7fpj2Q1WK0mVVV7zpCduLmsnv871rpyWkFdDhbSX6aHTvoM/GEGb5YYHwOF3Dj5BpV1Y9eHhMUaq9dLO50AbxaSDeUTUL9knDprQ0b+c4MskVtxovrJmyejkFeoot5xycevSPjlyncvxky/KPKvxfnq59i48AM2aopiUXnWitIOmNVoatgmALjr6XVHzDSlMhtLOl+Osp+VXhDROyql5Y61KtBU77mfmN+ZNmWApNLecz7PD5UlNqEV23SuHj9ChRxOLFd/N90tiBBxbrFWvVnsi4S8x0B6igM8TKhAo4o=
