sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
language: java
jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
install: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c17461eb5b3d00b3656d
    on_success: change
    on_failure: always
    on_start: never
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: jM56HBnAOLVNw6IaS5M0y4SSSIxNAlhwaeRXOTaZB3zc/FirwvJf1cBRbm72nZVMgYpEBNc4yDvsunsalumJM6pSPtKrlsNEM5TFtfnhr+018Vu35Zr/Ysh858ydSjUOl2I9ji/EuIa3y0RO871fDf7zjDqdgnaJn+9LPC0LakZCn9W9N+rvS1okIcUwnjH+tmyqwILshdqZGAxcypQzSM+e9v2HDOubTARciibNIFefvxwBoA6ClYg5Nlsv+KyJbUZiPSVlKV3AQA5mX+0YoM4C46S5wf8WYjDxchN4QHCZiX7tmniF0Nwu5cR0EGkAacRoT4sMU7423YRMRdCCbVfMovqbIgRW+/dU1RWwBPMneBdRqTPQVVAkplI+rEXN3xTHzXumqnol9fZ9ZxCOTYYz1v/ZE77Gql/SLlDfJ2kQUvC0UiKaKQ2dZ83hyUFS987ZNgjm6T+We3FyQRvDYi1l/EIDYckz4Zjw3Z43cvzUYzYBhAWS3EPhwG6frMRP1UVYllBo7do3y2y6NKIvOa0R8z2QYjp1UNUrr1DjAE8uiNRbm4rG3Smr71VnGSTY2Be7ZAhJom/MbirxQ28ToJePBlqNQeebSC3m3HmvaohDT/6rYvXCZrDTNWViGihoQWusr4GSISqDOAKu1bruswLgzBwRLlcJzUFX0oERgNo=
  - secure: XHSpaVe4+5w8JGEI0qs6UcTVUDZom27BMNpgncgQzWnnVTa3hyMszweI1LTu859B27Bl1M6yd5fFOpUyXfHGPTpMSN/RwWN5fa/LVSge3FkfYUnIPun9xDQMGoiy4onNofzc9WqNO4D4kRAlonVDgK0GuRcyW4ok+1qASMiogMnAtzaFhdpIEQRUPjYyTUKIb/r+mLUQ6i9iAaPU2U+NQfl4A8mVCgG//BIlqGhv8Sp4zIokFFry5e+9675CynP/HoSFYsBiR51AFdp5X2t7oEVGP7OUI4VFfn07lK2QQtdDqQUN4pcRAyzJPEeUOYFKfUGw/lvIZNyqkqxGIZlI9IMhqXQcFEVlApT9pQ0E1g56JRCtwoK5FsPQM54aer5Z1FISGv6/JoqGyfhoMEDfwGVxo4y43dyWn132G9qGUAuKvAR+aWXZvihsxWYyd2XSneo8UrdYZ//CEQ/t3iK+cQUdmyaJvobRdpv+YGHmnH+K/cPZkKuJxMujRkYXUqSW/saX1hpI8PRZzL1NX2XlLVOSuVNwPC95M7lxtoMmKoFMgIZbxfS5hgv5HkXVtc9uGuLqNUxLdL/QXqvK0gnKDDbcF/knOrc/lFHeKtgf7e99BztrYYGUCLQCHWz95JNF+K/udI0W/wfxc4SfA3sAVXUnuKPQbr0OvK0A58fFllQ=
  - secure: oQcWFrCPSNhSTgqt4tly1XoELyKCSh9Sflyr+xD5Aqt8lF2NgE99enwZR44XI7Vht1v2JoZhXeg+wepX4++ra1XRcZloXV//eGAY6Td0oZpM9VQeyFCy9He+1Ti3rpZTQrCkSJ1GIyKU0ZWIOdQuD6KzwW5f4xMg6Nm/RdrRNOcSvI+VSu5Tz7u0zQKi6v7/xiKOMP4cV3v0DOzpfqKpz4yQPjdrSAcQCNgVR5vm9j69gV1+ynszum4rap6ZEWhfZigctE6jKdi2X3QVc4GImEpTqtGuMLHfmwrzsQiXJcX555s2DbEjKQpx9um2l/QtdytmWEK5OSebCN0X1sZ8bt3l706w7zx9+cd1o7Nc3AOumrIu4+NotJ1kOgBtcGOrvJv5arf4QqGeRLQvOIwdzNfFykV2evPzFFyTZDgAFd09rbJTwrOv3dXaTdZpDWWNhKn6JLu5YXvCvLU2zxx6XyWAUGjlBVAvb27/5ecwbRVnn/FenZUNUnqNS1yFJOB7CjsuW9Ay7xEABrDUEFpq5wZ8+dXX/Xs2ucpwoc3sHAzqXMEchxNQoMDllbeIhSH/AOdbogb2WqdSgTD5kuP0gsul2D0C4sLbFh78urMd/EEVSqGxz8jYKshbjatZZy4r8fkDaSah0K01qLSO+IOPA8iT+aRFy9qjbDjwgPv+Tk4=
  - secure: r0bUk+dgYc5wKCXwRnlxgK1vAzZGB1v2wP+AL7Hk/5PNEAqITcbR7plgVJ1jVawRMMqN61WhxFpi4LKfb/AQRQhMnBs3hzGkUIhQ14HQCfsri30kjweB57Maihq8+MfqGfwUS+j4162uk/CV9V/nK3Sl65v/sp9vd+tq1zN0MpEQbsC1fjEvXH3c2yduCDhxuOapRdHYoV50dPwt++qAKdfvioMe3z/ei8Ak3r86CvXMZkzjSfwQmeTIzJDP6FkpXVxqWDGiEe/NHrbzk8Z9KsYv+ic5+uK20idgd4w8c+Dv56hDOPGZLkzoUkvOhDGpSPo6ohayP8/fUfBxqiEaq+vN2M7cvHSjfO1rordNdGTC5ydO7eMAfLGSnyEIrLkjfLKgBVGboA3gbq2DBv2wFx2AHc5qjoUNoN6KF5HnptT/QVyctE3I9aWMuOSz7e6mX09UK8oXzG9wlXJJSOk+Px0h0+g/CQGKL5JvV8ZBu4Vx7HO4UWS4tGmLSoOQkrqqNeGkcP0sLwRuw/rcb2qp0Ap+nXdtb+jOYvaM3BkEPwFKAGBbfGaauA3dFlpJUMVmJuaUP3nfERjhlN80cpLPdd8FFNGZNVjeHahG/ZmegjE+lfVZ1vCs4m46vYapK2H+NuJv/y9D3QMExgjM71vkzXbJ55ppxIErrfr81Z5YBFY=
  - secure: YXiHzL/eerW4/OUF9wQPMKwU4ko8eHox2bhaHfdX+OwMaSqZB9qDupIswE/u6Y0KGIQl2QJDeEur9PZuAabpnNtzFMc2EztdP/I/38RuSCQ1y4YsXj358rSI16LKZsK0BnA6pNFPKg5ukLaDB0DIAejM1FlACSgc1Wvh17WZaTOLpcfTdIXUu6YWFU/2qW3ZTCfHQUZ9xyE9GQ4cbhu4Fb+QhX3mUS2Mj08DBOoaMo93a+WgozWXhsL6y5XusxIHQEJwBO00CowRhmCh9dfqhRx88o70j+15ZC/mSvqjJu5FLby6mgDNiJVI8t4KjwUOfFIw4tm9jq35BQ+gKzWiTVHrTtt/rv4DHCPCgDs4a2OwF08hzzB+m3u5W8f5E9IB1MZ7gVPvXt5jRth1hwBWeK9WHGWIZGB6KWUswiBxpL/AVj8gT/N+515UcoARHiILrRBuLHOnFDN/GGqwTyJaRWW5z7Vlz+uhfS6yZyJrcclnXlu/ITLR/vAcCiNUFvAcTSFnnDGo5cMbE3g/YccPozNrbp2pZvZqhLALSvkUshuum5d0iOc22fOUA/cgs1MyGByIglvoo9MCA6kTlYKY8iGzbh+sP+j9FpLgkyG/xW47vk/rf4wB9EUbXpSkeef4igYhRl41WGoSZEWER4exr13AKjzQRHfvAvRG/JcMrzY=
