sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
language: java
jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
install: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c17461eb5b3d00b3656d
    on_success: change
    on_failure: always
    on_start: never
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: TeCh9rRleTjwXliCMC8qEyNwOr0mLI1EPMruojn/i4pXAyptBx/deZ2ZQ8SxVrSv1whQzgDatHAfIpZDlHx/wCSXSzeREE2z09be4Cr+5tMMBfeRhPH9GnR6i8Z7+h7WvHJ6TSpSh6xMjGX/m4uZJ3epP0KVwBGGUFvGysPTTF0VXALDAKSJvwMbUi/7JMBDLo5xoUITDumrLvUc78DEUUc1ft8bUGMHrGMawW5ZCo00CU44vPHz7Pq7AkOpFPgO4e/OJxNHBJctkFiCJoa4AbGQQZAMVWu1y2oX5LxOhMqJZnTWdY+Ky1HS+ZR6yDZm1NdKM+Sf0lqz4z6eQo1n35od7UT1AaIel/T9Soy/EpcrlN2mmdA4W0oj9IZlxIwfAKUX+ZsrTu4umYNRiKyQ7OiXESV6m3N60k0TiQ05CYcrGQaOr9+JyYqWvdDoeMgOC3knPDYdVwtt0J4bEHnyMh76GV/kiZHvFIOB3VBAL40I2dIisriyak+Atj2rzo9TzOmj31viMO5/93nUPZhL0OJmMrMLJIISIvcdDGi1b+HvWlTLV7VH1wkxCl6se/zbfFfVPzjjhuW2aoZvDeAvyj4gizgSPZRzfUb8Bsy6e8UKWIfjoh3xUwTTNJlUztSKfK3X7jI1M35JQ/HQocmrEeTE9Fv7H+JfaY73VuYVg3I=
  - secure: ayXEau72jf2bH1pkX+hTdWSbEhZeqRZUO2/cZZ/zBLzMp73GnykioJ2EDZQlJfcea+MG8yMXStwftxhejAsyt5xbO++8LPQvjDAR8EiE6XvZOlfXCQvNXy8hy3jej7OFhtvQFNhuk79jIVACURWjwHLTa0Xzhr7wHLrRItyHe882qp99WA1zc8Cae2HYKAdfvf49sofqnooy75+oWi3bobjzLhMoGXXKzvDG8qR7m7OLdd+V7mpxyy6fiQAXb//Eun9RV0qQruuu7aRWdYiZWbjVBXrDFIrP1MlrABuECsztybm8cKoRnLm6DpLTqlskyesHCjOToRdZB+9uTZOdJObmReAhQBFAzCqGPQfhIekj4/ibkXFJGJg4F2MhC7NC0dQBv3QV3UQeDaFJZYDCqku++xXcc6mPi20+EcAgQmtXtYruQuKKfc+D18KhrbSZsNBPN6ZTTP2n//b8SXtkR26ewJBIo3JYpceQhwg7xafKa4NqG9pCM1j9TUE8hygBOPd95RzqPrzXbxf0RAIEiXZUDFaNdudWqCWaJ/IDQVR7LQyuSBZ3hqvC2V8UGIEy/cqIMshiTIkrZtFexplgXpdwkU2clOlyJRX3ZOj5NEhL8uUiPyqmwu8ynCUh8msyc2ZlL6xQ/In9+hwBIuC5g0XRQXyeuWXNYc93I4uwfwc=
  - secure: DhrDP5lFcuj3zSoKQ6DVECsdNhbfPq0vvMCFnnyCDLCvmuwXYKCEomb4kZbc4Gvdwyasbw5Rw8UV+XBmbCo231m5i9Sd9NxStqevM/LLq7J9WJV3F4OXtTYvmmLbRIgWZA5X9nxLyeq2t1O01GvSIEZppQS8/kweQ+ko5985gyYSceZVAVHjz50eu+CiDH8JIxtvqh5oQE4u4gmfZU//W9tIISfqNBRsMtLGbv2oKIVdVW8HBfU+Mr9zZJjpUaf7sO2CWmo5/ShfWeVbqAMcmQQd+9E4Xm2AengWpnbF2R10RQF5CNJVP6GrUqvuOehUl/2VC7U9WQgDcIa6MX8YdjH+v/PfsloWAnPDoeeLrJxQbH84SRkdKnLJ2KedPFPndF+JxtmjElc6nfYR+UUuJEKuh6G3qEzW2TJwIHnYwNBwbLpaUKJTB+EXrGhZrbuihGq5q+n9MSSQXLKR14CF99Q9fYJ8cYkLvyhf422xJh1sRVkKIIuOYtY+Gkiz4Eemw6Y+O1Aq8eCttRoVd/7Pms/Cz0VxhFKd1DUvO7Y/+kvm7ACdPuecePHO6puOBYrnOfJr7oqinyqNyXmi/oBzbRovC/9Psy99bKMYv9Us3lzxGv8LVatun/nrKtVbGbsD/8tJx7hebsFCI0RLQezK+Luuqt67BAVko/tL3463HDw=
  - secure: NePhCCiq3TEF7Gywd8dJBXLl6IdpzjHTieS35RqL6lhknNdL505edhAnpy7befPEZ/tmXWfb0LRBm5wnCQxw08ew32ZKIdBAW2ai6CoEFFpIVQ9ZLWNod5il40BIZClVazTmya/g11sERQHA+Ifdc+k4XSXMDUszzO8Gd/FlTeeIIUj+fSASsSqRZgT0y09PDyktD/85fU3nvWpLJ6IyJ+ZGYbAZwQNjDd3u8MHmSXK1qizpFvvpFfpdY55fHZ4LDpo0tRa6sgj8hqYursthuuZj0HQhef6M3iIrycDiACZMmWmMwSOaSozkma/yY/Xiky0mXGUZ9wKsEhL/61Aw8MsSKI1TFKd3MWKP9hnRLxViuDlqV+UQd1c/748UJQydsk+fgOwSL/aJjHYXrTl3MK+dHquNMa4tLdpakN49SPCnRKX1a+Uh7Zpt95Xe1m85ojrJhRhr7AM7zOMDr4tNbBh19tw4Ym+48FSPfE8A9r7o2jEj5kQblzIZiOXQQ5Smzx9PXQq8dTuCRYMkFhwK06B+cmJM//N+rRM6qEhy4m+HzvEkw+HLez7dxIlP9RQ6H7MSGWYA0H5tUUtMSqp/ll+Jbsxun+wtbMkRiG4QSsfw0IFJtAV8GifQCzIdc0HDyx4vyW3+xymuboizsx1xtJGKuPKBFEuEm7SXoNs3d+s=
  - secure: LEZr8Ks1rqhHa9xGk8BwJinfisfYT9CKn+JqD9pWew4QfIRaAfIEc/QFKsVZa603aHvGS9/7D5rDLAnGg5j8Qo38BRU7wQNUvafcNRwAe6wt4306kKTjBnCuYa2ktCTrMLItCL8OT/x/ynqsligtejRXu6Ou2IKAAyP+MeT5M18qA5w25M+z2fgNPdb45/Kb1G1GfvMCnPvojs6U2QH59G8w7/T1Qd8InQmluO9kC1OSKr98pgjS0eH47aPKBJJmCvMa2IMJU3qb239qlqkAhHFD76Cfcfpyu72gnVahSOqOupT1DEzLbR9x5YGyNqle9BynZcs3xzErYHU+ccuFIZuxRpvDCLAHgs4qL+n+aiVNC0jcyb+MOPNpSYAk9MEdnMdryjpwXJNUfQecfeUlkIdBCL2JlKMKIQcfZGPVcDb28VGKd6ADPcSybFsxHBjjhVhxXSb1IqCd5zrTbhNJwIVca/Gfsgcf0mryJeuHJg+FWA+i37VfWqKBYxZIPCKzRaY3qlysnz3E9Hx2iNCntrC7qQ6tt4gbDvB2t7k5clsc7kdMcjnaCYUHzsWHrU4uuGyZ1vl9+ghaUvfqbYSEXs84oUE8JtKhIVcPX73eB83PU8rjY3hVzby9drgid9ogqOFXq5RM+M1mk2UAC1AvI/lm7waoZGjaNk9c2K/tJ2Y=
