sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
language: java
jdk: oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.m2"
install: true
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/c17461eb5b3d00b3656d
    on_success: change
    on_failure: always
    on_start: never
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc
  -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc
  -out $GPG_DIR/secring.gpg -d
- "$GPG_DIR/publish.sh"
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: RNZMtK4YqKlld/HgxOpvCRIGuP08a/41OSsqDAs3i7gw686HVR5s1G0eM/JOscG87/Kx6B1YHpXZkI0NRyQbTRQbrXm87A0biqcQLnHr8P4I1um/z2N5DUAYCcXUMyvngI6LMHMDJYv6ET/rtQHRDnW8R/yyIei9U+/EzHeU7fMJ5OdUzlrES3xHiXQGB+/vYb8CT//XYpSM+bOl+US5vkgfdKsb/Pu56zG2Vn1oYsT61cTHPBIFjsamZfWauGC5gNQ4BrmJ+X1ydtxKn55T+n+6vBK4UGzAdPeDz3KZW0MH0zPn8937z+Rppp/pAlf9/gXQjK+iRA2pnsyx0H93vP8k6bMgsnVwGE/4DShTONI9GjnMeNmejBVj3AauMrIWLtWzH3ix2EuZJWMHfl+aQLc7JJe7lgDp56XN4RwPE0+CmxfeNjLWFmIGm1muDQd1JiBu7cRDM9BzW5nmx2DPJQeQlNiQWbQwWTkCqT66kOuAd8FfKC+GvQ0uXDT/tW3WPjFKnhchZZG1LyzE++EDiv+FE9zv+6W3wNp+bv/fC6SdddDoQJvuNaErahJQ9bUkrDqMBTeKD7+jXQ6Xdq3q5jdBSrGo6TevN2CJaF8zOG5dYpiFTawU8qhXvRNlnCP1h1Cq3KmyEgIxIICdluFv87bvLQ89sArMt9zdhLxzZ2I=
  - secure: XhmaRcTXIm+iiemKEHdt+rBxixkQc71nnLJt69EWmpcPZloOSdv2hIDGXfOo/DzJ5c1DTY93TtIqpRdg9/5rCGtyIW2jtRFkj6Gfq9TKiPELnI1RFcWVYJAzGOWjTXfbZjZnUhG+oNP2rLpO6zv5o/R00U371sJL84GVm5wrMG7OUaI8jp2ylhLMA65WHRQuEmcaB4pyBxWYkEIJ1nSY8O+0jicTrq/zEyLKUtXP0ZK2EbSsXGymXiFU18ReM38xjodVOeiySe3u+/eqGfVnz3wOCtEaDK9Czpe/qXp2KqdX3dComhal8kJ8XLCc88VpwtjQk6MfpROkyTELayE8JY4UfcDX7N7gIqc1PBVwEPL9a6+29lbV70EbZi5YxJNoWwpvAy2mj3Ndwrg/6Ax/7/dfJkcu1i2eXogUW+5zxTZL4EYvy0WSQogGczxSfWsAxMbMx3I+E9yug8EgcCHl8N9F+9qjcenvlqNmWDY8/LCbBpTSqd5bOLW2BHrxy3KiN12jPSJUkLcFZJPF4NClZWgTHSAv9WKN+DmBWZeM4jOZdNyVkJMvF3qoEc56x7KDy2O+jADqdf+9aipXYGGOIBjD6Q+5mEpqYv9F8j8Q6PI0PuC0LbmasXmxcBA5tztPWBM2UgSlOPAbQVCXOVoqeOBqUamW3Mds7eeIZSSlis4=
  - secure: hs9BPaPv7aIOnBhd2Rk+7lhmB1onCVTII8+RPJI3vtFqUJ6/iKbQvgiMU+SWRJkTcySAdCCmye7CQvebYSwgb314Pj+e2HUOznsdpeRdJN/Ngem91Fo8GUoiagf/getsVRjrLTqUVCeq8ODkODNkCNDKchBN5OmMZkhkYYMkbw4rgA+TbYb0Hg4LyfhVPWc2EKhFDQL6xvrlFfLmoISLtArjieFR3nXV/TldBTF7btMECeqAD9zYXfD+CrNvsZqLN0/k7rFn3XUQMEFzevImGVElndxOqcvQPk5H6Ak8ibl+SxcRAW1ClhDd8yfsKBiaYob3y3kTEywOdmIRTr8SyJIVsWIh4CpNHPWPwP1RrEQGAlmWvbfWnQOxCaJ9a2D/fDCltqFUkk+xdwQFxela+bJR7O+PxoQNrCq7JEuD5w1NyQyGBvBPpS3lz9kBrvEop6I5r/cfiORv8cIYgySKDMIh2oGO/CmZ5NDk4uVEvOD6tUzDiCIS3V1zBYtvDSPh8DO1J8AYP35qVcjjUJrfhZiEH/CRB4ob/KmhPpDgIP3KX8mSo1I0LiQNsflXuLON+tWU6eoRJmO8AgFWkpx72RxOkC1JX2kEKU8JDEad05fMMEWl7ydgCzYMCyXzsTxV/RCJZDoEzrsTsWsUIRbt80G64IzWV/ltkl0I2g8XzXg=
  - secure: QsXX3KQyvwZ4Chf428RZOQaD7jAvrBSDQ44/7zphHEUOiyRM+/PkodX7da49DZBznLUI2CnB0NyS/Escsd10aV0+KQTM017y0zuJpn3mXVbGQEGuSYDg0WALQ9+D2uvS1HoG44OG/7WoLmat3iBnBlzMIt9Yg2PUGCLoW6wyTg1cnBoI17vvo6yqLAwPjYBhCT2exbT4Kc+jmaLZ3CCOzKYPWDB61G4hqwJjBk1tdrztQfXrb6G2pXWf/kTbrWTwTxe8JSox/3Vq4aDRgQbH+w2dE+nLNkwV5y+2pwzaMEOlQP7rHbwBnO7MdX4Po8Bw89nYt9CoRJbzvhY0kkcE0sOCzfd9XqeK4V68XVfoLZAcvzZ+yMNdE41/EISux/Qu+OOG0qolWJxKm942FgJxuuHnojcxzBM+OR5ORoQWoowmOHtXSUIzX5OGBMDqVjp6VRjsNTQMlN9546YKMorVMoJ2s+hobN9kyziSF+K7Y2tcX7ZOJ2bwQY4n5MMuDaymf1qUoXUL+8elT8WGETTVCFoIWE4Pvs4dTTECA6YrDl8iL6XT/N+U7tZJs6ts8q8E2xcVXErTCpE3TXZFwBQfiM7Ymt4ANHqjw27YhO4Ix2hjAFwR+mEiuKgXBL9FHM5r0fAdbiz+swTWLe/27hZXysSpAOnHFoabNsyiEvfLp+0=
  - secure: V6DQsvdXU5HPqyXqXC+wQQOEMmq5dwsXODN2oNAAWsetHrIZuOhePgedAvg0alEhCRLhcjF51mz7WlMxlLz5xGA0hWZ3mucavZqmvHLzfEXrnINa66nZOqYoHP5yBncbwu9rMS9CsvbWP9TxD6fQm+NE30HLp1FR6o3/vomiHDkzhQ0+5y4o2pjiuv/6Yup0vmsL24sN7XSVqwOClBl4rK4fZkLeLhRr9z96UP2Gs2RH9WriafC2sJsP9GAhf/IYNutPy31qhX1Do2pFMSc/oXwuPTCx2thYPRY1KHyP4zre2q5u+ByEn6mE2gXxQ6J3xgkRXuLCVkLkJK8PQt7Wq2x6lpP1VZH2lcB/uJPFI1myFHu1XahNxW8CMyhNVwGGgCblov88YkQbTnov+kMBpJ/j/70VRMRSogbWrh+h4wZYa+YsYRY3WzAc7WEY+ZLwN1O0kqjEMF2cz2fmTDA+MOoddIehfI0+zMNPxyKKy8yQwLyxrfQANPLdIbCpDI5A8MGdnR6TPqkD4fxXakpSj7UEn5pgdtegyox3xCJ4CPCg+VCtx24n+MdYEjndMQ77RrVD+9wm60uOG/N02GrTAmhTtS4OUKOLVWGL385wu9daHq/gKF8Pq/as7DohvlXPROQH5FCFkwjGe+CKAooCDesOBNmDb5fFwg5PZk/3JSk=
